spring:
  application:
    name: docker-demo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://mysql-server:3306/docker_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    name: root
    password: raIn4ugust
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
